name: personal_expense_tracker
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.68.0




